C_OPERATION_NOT_SUPPORTED = 'Operation not supported'
C_FAC_SET_COLUMN_LIST = ["factset_id", "ubs_id", "index_description", "DATE", "return"]
C_EXCP_DATA_COLUMN_LIST = ["source_table_nm", "exception_type", "load_status", "exception_desc"]
C_FACT_BENCHMARK_ROR_COLUMN_LIST = ['instrument_id', 'currency_cd', 'source_system_id', 'effective_dt', 'benchmark_ror_rt', 'firm_id', 'active_flg', 'batch_dt',
                                    'created_program_nm', 'created_user_nm', 'created_ts']
C_FACT_HOLDING_AGGR_SRC_SYS_LIST = ['BPSA']
C_CREATED_PROGRAM_NM = "GLUE_BATCH"
C_CREATED_USER_NM = "GLUE_BATCH"
C_TIME_STAMP_FORMAT = "yyyy-MM-dd HH:mm:ss"
C_DEFAULT_START_DATE = "1753-01-01"
C_DEFAULT_END_DATE = "9999-12-31"
C_DATE_FORMAT = "yyyy-MM-dd"
C_BASE_CURRENCY_PROPERTY_ID = 11
C_FAC_SET_CLIENT_NUMBER = "FACTSET"
C_RIMES_CLIENT_NUMBER = "RIMES"
C_KEY_TRANS_CLIENT_NUMBER = "KEYBANK"
C_KEY_RECON_CLIENT_NUMBER = "KEYBANK"
C_FIRM_ID = 1
C_FACTSET_DATE_FORMAT = 'yyyyMMdd'
C_BOOLEAN_DEFAULT_VALUE = 't'
TRUE_VALUES = [ 't', 'true']
FALSE_VALUES=['f', 'false']
C_BATCH_DATE_FORMAT = '%Y-%m-%d'
C_FACT_CLASS_ENTITY_CLM_LIST = ['entity_id', 'class_type_id', 'entity_type_cd', 'overriding_entity_type_cd', 'overriding_entity_id', 'effective_from_dt', 'effective_to_dt',
                                'allocation_prcnt', 'firm_id', 'active_flg', 'batch_dt', 'created_program_nm', 'created_user_nm', 'created_ts']
C_OLD_REC_INDICATOR_CLM = "old_record"
C_PACE_SEC_CLM_LIST = ['cu_ref', 'eligible_cd', 'filler', 'fired_cd']
C_CONVERSION_USER_NM = "GLUE_CONV"
C_REGION_NM = 'us-east-1'

C_POSVAL_CLIENT_NBR = "CONV"
C_H2B_CLIENT_NUMBER = "H2B"
C_BENCHMARK_CLIENT_NUMBER="CONV"
C_FISCAL_CLIENT_NUMBER="CONV"

C_529_CLIENT_NUMBER = "529"
C_ANNUITIES_CLIENT_NUMBER = "ANN"
C_CAPS_CLIENT_NUMBER = "CAPS"
C_COMMON_SOURCE_SYSTEM_DESC = "BPS BAS 0003"
C_COMMON_SOURCE_SYSTEM_ID = 3
C_REVPORT_CLIENT_NUMBER = "REVPORT"

# Constant for Schema Changes
C_SCHEMA_FILE_SEP= '|'
C_SCHEMA_TABLE_COLUMN_NAME= "table_name"
C_SCHEMA_ORDER_CLM_NAME= "order"
C_SCHEMA_DATA_TYPE_CLM_NAME= "data_type"
C_BASE_CURRENCY_PROP_DESC = 'BASE_CURRENCY'

C_CPOS_CONV_DT="CPOS_CONV_DT"
C_CPOS_DATE_FLG="WD"
C_CPOS_NUM_MONTHS = -24

C_FACT_HOLDING_AGGR_SRC_SYS_LIST = ['BPSA']
C_UTF_NULL_CHAR = u'\u0000'

C_DEFAULT_DECIMAL_TYPE="Decimal(26,10)"

C_TYPE_9_EXCLUDE_PROPERTY_DESC = "TYPE_9_EXCLUDE"
C_MULTI_CURRENCY_PROPERTY_DESC = "MULTI_CURRENCY"
C_SECURITY_OPTIONAL_PROPERTY_DESC = "SECURITY_OPTIONAL"
C_EXCLUDE_SECURITY_PROPERTY_DESC = "EXCLUDE_SECURITY"
C_DELAYED_BOND_PAY_DAYS_PROPERTY_DESC = "DELAYED_BOND_PAY_DAYS"
C_EFFECTIVE_DT_TARILER_FLG_PROPERTY_DESC = "EFFECTIVE_DT_TARILER_FLG"
C_MULTI_CURRENCY_SUPPORT_PROPERTY_DESC  ='MULTI_CURRENCY_SUPPORT'
C_BACK_DATED_TRANS_PROPERTY_DESC = "TRAN_BACK_DT_B4_CONV_FLG"
C_CANCEL_TRANS_PROPERTY_DESC = "TRAN_CANCEL_NEW_MTCH_FLG"

C_EMPTY_FILE_LOG_MSG = "File is empty from source, Hence Skipping job run"

C_CLM_NAME_FORMAT_CREATED_USING_PIVOTED = "{pivot_clm}_{agg_fucn}({clm_name})"

C_DIM_INSTRUMENT_COLUMN_LIST= ['INSTRUMENT_ID','ISSUE_DT','START_DT','MATURITY_DT','END_DT','FIRST_ACCRUAL_DT','FIRST_COUPON_DT','PRE_REFUND_DT','SOR_INSTRUMENT_ID'
    ,'INSTRUMENT_DESC','SOURCE_SYSTEM_ID','CURRENCY_CD','INSTRUMENT_NAME_1','INSTRUMENT_NAME_2','INSTRUMENT_TYPE_CD','CONSTITUENT_BENCHMARK_ID','CONSTITUENT_BENCHMARK_START_DT'
    ,'CONSTITUENT_BENCHMARK_END_DT','CONSTITUENT_BENCHMARK_PRCT','QTY_FACTOR_VAL','INTEREST_RT','COUPON_FREQ_CD','PENDING_PAYMENT_DAYS','OPT_CALL_PUT_FLG','OPT_STRIKE_PRICE_AMT'
    ,'UNDERLYING_INSTRUMENT_ID','YEAR_COUNT_CD','DAY_COUNT_CD','INTEREST_RATE_TYPE_CD','FIRM_ID','ACTIVE_FLG','BATCH_DT','CREATED_PROGRAM_NM','CREATED_USER_NM','CREATED_TS'
    ,'MODIFIED_PROGRAM_NM','MODIFIED_USER_NM','MODIFIED_TS']

C_BENCHMARK_CLIENT_NUMBER='CONV'


C_DTL_INSTRUMENT_REF_FIELDS = ["instrument_id", "source_system_id", "instrument_ref_type_cd", "instrument_ref_nm", "start_dt", "end_dt", "firm_id", "active_flg", "batch_dt",
                               "created_program_nm", "created_user_nm", "created_ts", "modified_program", "modified_user", "modified_ts"]
C_GIM2_CLIENT_NUMBER = "GIM2"

#constants for custom code
C_MULTI_CURRENCY_SUPPORT_PROPERTY_DESC = 'MULTI_CURRENCY_SUPPORT'
C_OPTIONAL_SECURITY_PROPERTY_DESC = 'OPTIONAL_SECURITY'
C_RECYCLED_SECURITY_PROPERTY_DESC = 'RECYCLED_SECURITY'
C_EFFECTIVE_DT_TRAILER_FLG_PROPERTY_DESC= 'EFFECTIVE_DT_TRAILER_FLG'
C_TRAILER_TRANS_TYPE_ID_FLG_DESC= 'TRAILER_TRANS_TYPE_ID_FLG'
C_CLASSIFICATION_DERV_FLG_DESC='CLASSIFICATION_DERV_FLG’'
C_TRAILER_EFFECTIVE_DT_FLG_DESC='TRAILER_EFFECTIVE_DT_FLG'

C_PROSPECTUS_BEN_CLIENT_NUMBER="CONV"

C_DATE_DTPE_CD_ACLDT='ACLDT'
C_DATE_DTPE_CD_PRGDT = 'PRGDT'
C_DATE_DTPE_CD_FOADT='FOADT'
C_DATE_DTPE_CD_AOPDT = 'AOPDT'
C_DATE_DTPE_CD_ADPDT='ADPDT'
C_DATE_DTPE_CD_OPDT = 'OPDT'
C_DATE_DTPE_CD_CLDT = 'CLDT'
C_FAD_DATE_TYPE_CD_ADPEDT="ADPEDT"
C_FAD_DATE_TYPE_CD_ACLDT="ACLDT"
C_FAD_PROGRAM_CD_MAM="MAM"
C_FAD_PROGRAM_CD_MAI="MAI"
C_FAD_PROGRAM_CD_MA7="MA7"

C_INSTRUMENT_REF_TYPE_CD_BEN_MF= "MF"
C_INSTRUMENT_REF_TYPE_CD_BEN_CU= "CU"
C_INSTRUMENT_REF_TYPE_CD_BEN_IS= "IS"
C_INSTRUMENT_REF_TYPE_CD_BEN_OT= "OT"
C_INSTRUMENT_REF_TYPE_CD_BEN_PW_SEC= "PW_SEC"
C_INSTRUMENT_REF_TYPE_CD_BEN_FIID= "FIID"
C_ADVISORY_VALUE_FOR_PROGRAM_IND_NULL= 'ADV'
C_CHILD_CLASS_TYPE_CD_WITH_ADV_REC = []
C_CHILD_CLASS_TYPE_CD_WITH_NON_ADV_REC = ['Insurance & Annuities']
C_DIM_CLASS_SEC_TYPE= 'SEC_TYPE'

C_DEFAULT_TRANSCATION_CD=-99999
C_DEFAULT_TRANSCATION_IND="N"

C_ACCOUNT_REF_TYPE_CD_SOR = "SOR"
C_ACCOUNT_REF_TYPE_CD_OW = "OW"
C_ACCOUNT_REF_TYPE_CD_UAN = "UAN"
C_ACCOUNT_REF_TYPE_CD_KEYBANK = "KEYBANK"
C_ACCOUNT_REF_TYPE_CD_OW_ACCT = "OW_ACCT"
C_ACCOUNT_REF_TYPE_CD_BPS = "BPS"
C_DTL_ACCOUNT_REF_COLUMN_LIST = ["account_id", "account_ref_type_cd", "account_ref_nm", "active_flg", "batch_dt",
                                 "start_dt", "end_dt", "created_program_nm", "created_user_nm", "created_ts"]


C_REASON_CD_SRS = 'SRS'
C_REASON_CD_PACE = 'PACE'
C_REASON_CD_ZTP = 'ZTP'

C_SOR_BEN_INSTR_REF_TYPE_CD='SOR_BEN'

C_CAPS_ENTITY_TYPE_CD_LIST = ['CAPS', 'SECURITY']

C_FACT_MV_MUlTIPLIER_TYPE_CD_YTM= 'YTM'
C_FACT_MV_MUlTIPLIER_TYPE_CD_YTW= 'YTW'
C_FACT_MV_MUlTIPLIER_TYPE_CD_YTWRP= 'YTWRP'
C_FACT_MV_MUlTIPLIER_TYPE_CD_MD= 'MDUR'
C_FACT_MV_MUlTIPLIER_TYPE_CD_MCD= 'MCDUR'
C_FACT_MV_MUlTIPLIER_TYPE_CD_ED= 'EDUR'
C_FACT_MV_MUlTIPLIER_TYPE_CD_CNX= 'CNX'
C_FACT_MV_MUlTIPLIER_TYPE_CD_YTCRP= 'YTCRP'
C_FACT_MV_MUlTIPLIER_TYPE_CD_YTC= 'YTC'
C_FACT_MV_MUlTIPLIER_TYPE_CD_EAI= 'EAI'
C_FACT_MV_MUlTIPLIER_TYPE_CD_AAI= 'AAI'

C_INSTRUMENT_REF_TYPE_CD_PW_SEC = 'PWSEC'
C_INSTRUMENT_REF_TYPE_CD_FIID = 'FIID'
C_INSTRUMENT_REF_TYPE_CD_OT = 'OT'
C_INSTRUMENT_REF_TYPE_CD_PRO_I="PRO_I"
C_INSTRUMENT_REF_TYPE_CD_SY="SY"
C_INSTRUMENT_REF_TYPE_CD_SED="SEDOL"
C_INSTRUMENT_REF_TYPE_CD_DESC="DESC"
C_INSTRUMENT_REF_TYPE_CD_CU="CU"
C_INSTRUMENT_REF_TYPE_CD_BEN="BEN"
C_INSTRUMENT_REF_TYPE_CD_INSU = 'INSU'
C_INSTRUMENT_REF_TYPE_CDS_INSU_PW_SEC_ID  = ['PW_SEC','PWSEC']

C_ENTITY_TYPE_CD_SECURITY = "SECURITY"
C_RELATION_TYPE_CD_MFS = "MFS_SEC_TYPE"
C_BIR_RELATION_TYPE_CD_ROOT ="ROOT"

C_DTL_ENTITY_REF_ENTITY_TYPE_CD_SLEEVE="SLEEVE"
C_DTL_ENTITY_REF_ENTITY_REF_TYPE_CD_VM="VM"

C_CONV_SEC_REF_TYPE_CD_IN = ['OT','FIID','PRO_I','PW_SEC']
C_BRDG_ACC_REL_ENTITY_TYPE_CD_SLEEVE = "SLEEVE"
C_BRDG_ACC_REL_ENTITY_TYPE_CD_FOA= "FOA"
C_BRDG_ACC_REL_ENTITY_TYPE_CD_BU='BU'
C_BRDG_ACC_REL_ENTITY_TYPE_CD_ADVISOR="ADVISOR"
C_BRDG_ACC_REL_ENTITY_ID_DEFAULT="1-Default-1"
C_CARMA_CLINT_NBR_NUM = "CARMA"
C_DEACTIVE_FLG= 'f'


C_PERF_LEVEL_FLG_TOT = "TOT"
C_PERF_LEVEL_FLG_ADV = "ADV"
C_LINK_TYPE_CD_LCO = "LCO"

C_CHILD_CLASS_TYPE_CD_FI_YLD_WRST_TYP_C = 'YTW_REDM_TYPE_FLG'
C_CHILD_CLASS_TYPE_CD_FI_YLD_WRST_STYP_C = 'YTW_REDM_STATUS_FLG'

C_SM_SECRATING_CHILD_CLASS_TYPE_CD = ["RATING_FITCH","RATING_FITCH_ENC","RATING_FITCH_UND","RATING_MOODY",
                                      "RATING_MOODY_ENC","RATING_MOODY_UND","RATING_SNP","RATING_SNP_ENC","RATING_SNP_UND"]


C_SEC_OTHER_CLIENT_NUMBER='SEC_OTHER'

C_FCE_ENTITY_TYPE_CD_SEC ="SECURITY"
C_FCE_ENTITY_TYPE_CD_ACC ="ACCOUNT"
C_FCE_ENTITY_TYPE_CD_TMPLT_F="TEMPLATE-FULL"
C_FCE_ENTITY_TYPE_CD_TMPLT_P="TEMPLATE-PARTIAL"
C_FCE_CLASS_TYPE_CD_TAX_FLG = "TAX_FLG"
C_FCE_CLASS_TYPE_CD_AMT_TAX_FLG = "AMT_TAX_STATUS"
C_FCE_CLASS_TYPE_CD_PR_TAX_FLG = "PR_TAX_FLAG"
C_FCE_CLASS_TYPE_CD_CNTRY_ISSUER = "COUNTRY_CD"
C_FCE_CLASS_TYPE_CD_STATE_CD = "STATE"
C_FCE_CLASS_TYPE_CD_BOND_STATUS = "BOND_STATUS"
C_FCE_CLASS_TYPE_CD_SEC_USAGE = "SEC_USAGE_CD"

C_DFS_SCH_TYPE_CD_FI_PUTSCH = "FI_PUTSCH"
C_DFS_SCH_TYPE_CD_FI_CALLSCH = "FI_CALLSCH"

C_CONSULT_TYPE_CD='CW'

C_DIM_CLASS_TYPE_CHILD_CLASS_VAL_COMMITMENT="COMMITMENT"
C_DIM_CLASS_TYPE_CHILD_CLASS_VAL_DISTRIBUTION="DISTRIBUTION"
C_DIM_CLASS_TYPE_CHILD_CLASS_VAL_CONTRIBUTION="CONTRIBUTION"
C_FACT_CAPITAL_FLOW_FEE_AMT_FLG_FOR_COMMITMENT="COM"
C_FACT_CAPITAL_FLOW_FEE_AMT_FLG_FOR_DISTRIBUTION="DIS"

C_LINK_TYPE_CD_BRNCH= "BRNCH"
C_DCT_CHILD_CLASS_TYPE_CD_SEC_TYPE="SEC_TYPE"
C_DCT_CHILD_CLASS_TYPE_CD_CAPS_SEC_ASSET_CLS="CAPS_SEC_ASSET_CLS"

C_DCT_CHILD_CLASS_TYPE_CD_SEC_CLASS="SEC_CLASS"
C_DCT_CHILD_CLASS_TYPE_CD_SEC_ASSET_CLASS="SEC_ASSET_CLASS"
C_DCT_CHILD_CLASS_TYPE_CD_SEC_ASSET_CATEGORY="SEC_ASSET_CATEGORY"
C_DCT_CHILD_CLASS_TYPE_CD_SEC_MKT_GROUP="SEC_MKT_GROUP"
C_DCT_CHILD_CLASS_TYPE_CD_ACC_DVP_FLG="ACCOUNT_DVP_FLG"
C_DCT_CHILD_CLASS_TYPE_CD_AIP_SEC_TYPE="AIP_SEC_TYPE"

C_DCT_CHILD_CLASS_VAL_EQUITY="Equity"
C_DCT_CHILD_CLASS_VAL_OTHER="Other"
C_DCT_CHILD_CLASS_VAL_IA="Insurance & Annuities"
C_DCT_CHILD_CLASS_VAL_CASH="Cash"
C_DCT_CHILD_CLASS_VAL_ASSET="ASSET"
C_DCT_ENTITY_TYPE_CD_SECURITY="SECURITY"


C_BENCHMARK_INSTURME_DESC_SECURITY_WEIGHT_SEP_CHAR = "% "
C_BENCHMARK_INSTURME_DESC_SECURITIES_SEP_CHAR = ","

C_BRDG_INST_REL_ENTITY_TYPE_CD_BENCHMARK= "BENCHMARK"
C_BRDG_INST_REL_RELATION_TYPE_CD_P_BEN= "P_BEN"
C_BRDG_INST_REL_RELATION_TYPE_CD_S_BEN= "S_BEN"
C_BRDG_INST_REL_RELATION_TYPE_CD_BEN_POSTFIX= "_BEN"
C_BRDG_INST_REL_RELATION_TYPE_CD_PP_BEN="PP_BEN"
C_BRDG_INST_REL_RELATION_TYPE_CD_PP_BEN_M="PP_BEN_M"

C_BRDG_ENTITY_REL_RELATION_TYPE_CD_P_BEN= "P_BEN"
C_BRDG_ENTITY_REL_RELATION_TYPE_CD_S_BEN= "S_BEN"
C_BRDG_ENTITY_REL_RELATION_TYPE_CD_BEN_POSTFIX= "_BEN"
C_BRDG_ENTITY_REL_ENTITY_TYPE_CD_BENCHMARK= "BENCHMARK"
C_BRDG_ENTITY_REL_ENTITY_TYPE_CD_FOA= "FOA"

C_BRDG_ENTITY_REL_ENTITY_TYPE_CD_PROGRAM= "PROGRAM"
C_BEN_DIM_INSTRUMENT_SOR_REF_PREFIX = "BLND_"

C_DEFAULT_SLEEVE_ID_TRANSACTION_VALUE = -1

C_BRDG_ACC_REL_RELATION_TYPE_CD_P_BEN= "P_BEN"
C_BRDG_ACC_REL_ENTITY_TYPE_CD_BENCHMARK= "BENCHMARK"

C_TABLE_EXCEPTION_TYPE_E="E"
C_TABLE_EXCEPTION_TYPE_R="R"
C_TABLE_LOAD_TYPE_N="N"

C_BASE_SLEEVE_SWP_ACCOUNT_VALUE="0000"

C_CAPS_SEC_STYLE_CHILD_TYPE_CD="CAPS_SEC_STYLE"


C_FACT_ACCOUNT_SLEEVE_LINKING_ELIGIBLE_PROGRAM_MNG_CDS= ['MAM']

C_SECURITY_GICS_CLS_CHILD_TYPE_CD="SECURITY_GICS_CLS"

# constants for carma_option_overlay
C_FACT_CAPITAL_FLOW_FEE_AMT_FLG = 'MDT_AMT'
C_FACT_CAPITAL_FLOW_FEE_AMT_FLG_1 = 'TCI'
C_FACT_CAPITAL_FLOW_FEE_AMT_VAL_TCI = '0'

C_FACT_ACCOUNT_DATE_ENTITY_TYPE_CD_SLEEVE="SLEEVE"

C_PROD_CD_INCOME_TYPE_I="I"
C_PROD_CD_INCOME_TYPE_D="D"

C_INSTRUMENT_BOND_STATUS_CHILD_CLASS_CD = 'BOND_STATUS'
C_RATING_SNP_CHILD_CLASS_CD = 'RATING_SNP'
C_RATING_SNP_UND_CHILD_CLASS_CD = 'RATING_SNP_UND'
C_RATING_MOODY_CHILD_CLASS_CD = 'RATING_MOODY'
C_RATING_MOODY_UND_CHILD_CLASS_CD = 'RATING_MOODY_UND'
C_RATING_FITCH_CHILD_CLASS_CD = 'RATING_FITCH'
C_RATING_FITCH_UND_CHILD_CLASS_CD = 'RATING_FITCH_UND'

C_DIM_CLSS_TYPE_CHILD_CLASS_TYPE_CD_CUST_BLND_FLG= "BLND_TYPE_CD"
C_DIM_CLSS_TYPE_CHILD_CLASS_VAL_CUST_BLND_FLG='ct'

# constant for conv_ben_nominal_fact_class_entity
C_FACT_CLASS_ENTITY_CHILD_CLASS_TYPE_CD_NOM = 'NOMINAL'
C_BRDG_ENTITY_REL_RELATION_TYPE_CD_ADVISOR= "ADVISOR"

C_DTL_ENTITY_REF_ENTITY_TYPE_CD_ADVISOR= "ADVISOR"
C_DTL_ENTITY_REF_ENTITYT_REF_TYPE_CD_FA= "FA"

C_DIM_CLSS_TYPE_CHILD_CLASS_TYPE_CD_MULTI_PRD_BLND_FLG= "MULTI_PRD_BLND_FLG"
C_DIM_CLSS_TYPE_CHILD_CLASS_VAL_YES='yes'
C_DIM_CLSS_TYPE_CHILD_CLASS_VAL_Y='Y'

C_FACT_CLASS_ENTITY_REL_ENTITY_TYPE_CD_BENCHMARK= "BENCHMARK"

C_DI_INSTRUMENT_TYPE_CD_SEC = 'SEC'

C_DIM_SOR_TRN_GRP_ID_TYPE_GRP='TRAN_GRP'
C_DIM_SOR_TRN_GRP_ID_TYPE_REP='REP_BEHAVIOR'

C_FOA_BEN_TGT_ACC_STG_ACTION_DE_ACTIVE="de_active"
C_FOA_BEN_TGT_ACC_STG_ACTION_DATE_SHIFT="date_shift"
C_FOA_BEN_TGT_ACC_STG_ACTION_BLEND_CHANGE="blend_change"
# fact_sor_holding
FSH_POS_BAL_FLG_BALANCE="B"
FSH_POS_BAL_FLG_POSITION="P"
C_BUB_RECORD_TYPE_CD='BUB'
C_HUA_RECORD_TYPE_CD='HUA'

BPS_SOR_ACCOUNT_START_WITH="5"

C_FACT_CAPITAL_FLOW_FEE_AMT_FLG_F = 'F'



C_API_INSTRUMENT_REF_NAME_PREFIX="JT%"

C_DIM_CLSS_TYPE_CHILD_CLASS_TYPE_CD_SECURITY_PROD_CD= "SECURITY_PROD_CD"

C_DIM_CLSS_TYPE_CHILD_CLASS_VAL_MF = ['MF Rvse Load Prop', 'Mutual Fund Money Mkt', 'Reverse Load', 'Management Co Open End Fund',
                                      'Undefined Mutual Fund', 'Mutual Fund No Load', 'Mgmt Co Open End Fund Prop',
                                      'MF Money Mkt Prop', 'MF No Load Prop', 'Mgmt Co Pace Fund Prop']

C_DIM_CLSS_TYPE_CHILD_CLASS_VAL_ETF = 'Management Co Closed End Fund'

C_DIM_PRG_PROGRAM_CD_MAM="MAM"
C_DIM_PRG_PROGRAM_CD_MAI="MAI"
C_DIM_PRG_PROGRAM_CD_MA7="MA7"

# conv_upav_dim_advisor
C_DTL_ENTITY_REF_ENTITYT_REF_TYPE_CD_NFA= "NFA"
C_DTL_ENTITY_REF_ENTITYT_REF_TYPE_CD_OFA= "OFA"


DIM_INSTRUMENT_DESC_BENCHMARK="Manager Research - "

C_MTDT_ACC_BEN_ID_GEN_START_POS = 10000000

C_CNSLT_WORK_ACC_GRP_TYPE="ACCGRP"

C_ANNUITIES_INSURANCE_STUB_FUND_CNTRCT_RECORD_TYPE="CNTRCT"
C_ANNUITIES_INSURANCE_STUB_FUND_SUBFND_RECORD_TYPE="SUBFND"

C_FAT_PROGRAM_IND_MAK="MAK"

FACT_ASSETS_LIABILITIES_POS_BAL_FLG_BALANCE="B"
FACT_ASSETS_LIABILITIES_POS_BAL_FLG_POSITION="P"
C_FSL_ASSET_LIABILITY_FLG_ASSET = "A"
C_FSL_ASSET_LIABILITY_FLG_LIABILITY = "L"
C_FSL_OUTSIDE_FLG_OUTSIDE_FILE = "t"
C_FSL_INTERNAL_FLG_OUTSIDE_FILE = "f"
C_FSL_MANUAL_FLG_AUTOMATED_FILE = "f"
C_FSL_MANUAL_FLG_MANUAL_FILE = "t"
C_FSL_ACCOUNT_TYPE_CD_LIABILITY="L"
C_FSL_ACCOUNT_TYPE_CD_ASSET="A"


C_CONV_POS_TYPE_FILTER_VAL="IN0001"

C_UBS_LIABILITY_CLIENT_NUMBER="UBS"
C_OUTSIDE_ASSET_CLIENT_NUMBER="OUTSIDE"

C_DIM_PROPERTY_VALUE_DESC_N=['n','N']
CANCEL_TRANSACTION_STATUS_IND = "C"


C_DCT_CHILD_CLASS_VAL_NONUS_STATE='NON US STATE'

C_CSTM_BLNDD_BNCHMK_I_DEFAULT = "999999999"
C_CSTM_BLNDD_BNCHMK_X_DEFAULT = "Benchmark Not Assigned"
C_USR_CRTE_UUNM_I_DEFAULT = "Manual"

C_DEFAULT_SLEEVE_ID_TRANSACTION_VALUE_1 = 1

C_OTHER_DECIMAL_TYPE = "Decimal(8,2)"

C_NEW_INSTRUMENT_START_POSITION = 10000

C_CONV_FIHIST_CLIENT_NUMBER="CONV"

C_FACT_CAPITAL_FLOW_FEE_COMMISION_FLG_PRG_NM='H2A_COMMISSION_VAL'

C_DCT_CHILD_CLASS_TYPE_CD_BELN_TYPE="BLND_TYPE_CD"
C_DCT_CHILD_CLASS_VALUE_FOA_BEN="PM"
C_DCT_CHILD_CLASS_VALUE_CONV_450="CT"
C_DCT_CHILD_CLASS_VALUE_ACC_TGT="TR"
C_DCT_CHILD_CLASS_VALUE_MSTR_PROP="MP"
C_INSTRUMENT_REF_TYPE_CD_OSI="OSI"

# RMA constants
C_TRANS_BEHAVIOR_710_310="505"
C_TRANS_BEHAVIOR_700_300="705"

C_INSTRUMENT_REF_TYPE_CD_SD="SD"
C_CAPS_SEC_BRD_ASSET_CLS_CHILD_TYPE_CD='CAPS_SEC_BRD_ASSET_CLS'
C_CHILD_CLASS_VAL_LIABILITIES = ["1081","1134","1135","1136","1137","1138","1139","1140","1151"]

C_PRICE_TYPE_CODE='HPR'

C_CAPS_SEC_SUB_ASSET_CLS_TYPE_CD = 'CAPS_SEC_SUB_ASSET_CLS'

# RPT FOA Account
C_ACCOUNT_FAIL_CLM = "Rule failure"
C_ACCOUNT_RESTRICT_CLM = "Restricted"
C_ACCOUNT_NEW_CLM = "New Account"
C_ACCOUNT_MNGR_CHG_CLM = "Manager change"
C_CAPS_NODE_ID = '1053'
C_EXCLUDE_FLG = True
C_EXCLUDE_ACCOUNT_TYPE = ['5']

C_DTL_ACCOUNT_REF_REQ_FIELDS = ["account_id", "account_ref_type_cd", "account_ref_nm", "active_flg", "end_dt", "created_ts"]
C_TRANSACTION_BEHAVIOR_ID_REQ = ["4900", "4910", "1100", "1200"]
